import type { PlaybackMessage } from '../components/dialogue/DialoguePlayback';

/** Sample chunk phrase the demo dialogue below is built around — highlighted via DialoguePlayback's targetText, same as a real comic. */
export const GUEST_TARGET_TEXT = 'on second thought';

/** A hand-written sample dialogue for the guest gallery — no real character images or backend session needed (imageUrl: null renders an initials placeholder, see DialoguePlayback). */
export const GUEST_DIALOGUE_MESSAGES: PlaybackMessage[] = [
  { characterName: 'Alex', imageUrl: null, side: 'left', text: 'Do you want to grab lunch now?' },
  { characterName: 'Jordan', imageUrl: null, side: 'right', text: 'On second thought, let’s wait until after the meeting.' },
  { characterName: 'Alex', imageUrl: null, side: 'left', text: "Good idea — I'll see you then." },
];

/**
 * The "type an answer" preview reuses InteractiveWords with an empty
 * `parts` array, which falls back to plain `fallbackText` — the real
 * per-word tap-to-explain breakdown is generated by the backend per chunk,
 * not something worth faking for a static sample.
 */
export const GUEST_SITUATION_TEXT = "A friend suggests going out tonight, but you'd rather stay home and relax. How do you politely decline?";

export const GUEST_SAMPLE_ANSWER = "Actually, I think I'll just stay in tonight — but thanks for asking!";
